foreach(binary "${LIBRARY}" "${TOOL}" "${TESTS}")
    execute_process(COMMAND "${READELF}" -d "${binary}" RESULT_VARIABLE result OUTPUT_VARIABLE dynamic ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Cannot inspect ${binary}: ${error}")
    endif()
    if(dynamic MATCHES "NEEDED[^\n]*(libcrypto|libssl|composite|symcrypt|scossl|jitterentropy)[^\n]*\\.so")
        message(FATAL_ERROR "${binary} links dynamically to crypto:\n${dynamic}")
    endif()
    execute_process(COMMAND "${READELF}" --dyn-syms --wide "${binary}"
        RESULT_VARIABLE result OUTPUT_VARIABLE symbols ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Cannot inspect symbols of ${binary}: ${error}")
    endif()
    if(symbols MATCHES "(GLOBAL|WEAK)[^\n]*DEFAULT[^\n]* (OPENSSL_|EVP_|OSSL_|X509_|SymCrypt|scossl_|p_scossl_|jent_)")
        message(FATAL_ERROR "${binary} exposes or imports crypto symbols; private static crypto must not interpose with host crypto.")
    endif()
    execute_process(COMMAND "${READELF}" --program-headers --wide "${binary}"
        RESULT_VARIABLE result OUTPUT_VARIABLE headers ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Cannot inspect program headers of ${binary}: ${error}")
    endif()
    if(headers MATCHES "GNU_STACK[^\n]*RWE")
        message(FATAL_ERROR "${binary} requests an executable stack.")
    endif()
endforeach()
